### PR TITLE
Ticket/1307 Adjust size of .com to match area51s

### PR DESCRIPTION
**Pull request by hanakin**
going from 850px max-width which is a tablet screen size nowadays to 1152px which is the same as prosilver! 

screenshot 2017-10-15 11 20 27
screen shot 2017-01-10 at 5 40 02 pm

https://tracker.phpbb.com/browse/WEBSITE-1307

WEBSITE-1307

### CODE REVIEW

**Comment by hanakin** [comment]
@michaelcullum not pressing on this as I know your busy but its here when you get some time

**Comment by michaelcullum** [comment]
My main question is why? I'd like to see the implications of this honestly.

**Comment by hanakin** [comment]
why for a lot of reasons 

1. its extremely problematic to design at a resolution this small on desktop and allow for responsive flow on other devices. Most people use hd resolutions today anyway. 
2. Its hard to merge pro-silver into that small of a width to begin with I am not saying that it has to be 1152px but we should at least really consider following best practices in responsive design at a minimum which allows for 5 breakpoints small-mobile, mobile, tablet, desktop, desktop wide. The current resolution falls between tablet and desktop norms weirdly (https://v4-alpha.getbootstrap.com/layout/grid/#grid-options) this means you only really have 1 and a half breakpoints for responsive (as we currently merge small-mobile and mobile) and  it does not adhere to any kind of grid based sizing recommendations. making it extremely buggy/hacky.
3. Eventually we are going to have to completely re-design overhaul the whole thing when the new theme is available relying on a component approach. Which means a grid which means larger sizes anyway.

Ideally we should overhaul the responsive features ie remove them and redo them properly mobile first but that will be easier if we figure out the size so we can start using a freaking grid!

ps. sorry for ranting the codebase just brings it out of me

**Comment by DavidIQ** [comment]
I can get behind this. .com will eventually not look like what it does now so might as well start giving everyone a bit of a shock. 😃

I do worry that there might be something somewhere that takes into account the overall width when it comes to element style and position (*cough*Titania*cough*) but we can deal with those as they come up I think.

**Comment by hanakin** [comment]
screen shot 2017-01-10 at 10 45 39 pm

the responsive breakpoints may need some tweaking though

**Comment by iMattPro** [comment]
Is it fixed width? Might be good if it was fluid-width, with a max-width of 1152.

**Comment by hanakin** [comment]
@VSEphpbb its just like area51 fluid as you stated

**Comment by DavidIQ** [comment]
There's some of the modal boxes missing some style elements on .com (i.e. the closing x). Is this pr addressing that as well?

**Comment by hanakin** [comment]
@DavidIQ no I noticed that but have not been able to figure out what the cause is just yet.Other than the fact that its not a css fix but a template issue most likely related to SE on the community repo

**Comment by DavidIQ** [comment]
Do we still want to do this? There are merge conflicts.

**Comment by hanakin** [comment]
its most likely an easy fix for the conflicts, however I can not recall where I left off with the responsive tweaks if it was all accomplished or not...it does not matter to me either way, Its really up to everyone else

**Comment by DavidIQ** [comment]
If the header image expands, which it looks like it does, then I think we should just go ahead and do this so it's more like the default prosilver.

**Comment by JimMH** [comment]
Homepage does look strange like this with the four buttons and the blank space at the right. So we'll either need to center that, or change/add button(s).

**Comment by DavidIQ** [comment]
Right now they're all h2 tags (?) so maybe it should be redone to be a list and allow it to spread out in its row.

**Comment by hanakin** [comment]
If I remember then I'll look at it this weekend 😜 Then that is if i can get website working locally looks @marc1706 oh and @paul999 😜

**Comment by hanakin** [comment]
ok so fix the conflicts just need to review for any changes to responsive. The fix for the header banners is on another repo so will need to happen in the html there. We need to basically remove the h2 completely then tweak the css slightly... ps testing for me is difficult as I have no idea how to get .com running locally on my mac @marc1706

**Comment by marc1706** [comment]
@hanakin I'll try to go through the instructions again the next few days to make sure it properly works. I think all linux commands should more or less also work on mac.

**Comment by hanakin** [comment]
@marc1706 it most likely not the fact that im on a mac, but the fact that I use mamp for my environment which is a little different when dealing with the hosts and htcacess stuff. @VSEphpbb are you still running a mamp setup?

**Comment by marc1706** [comment]
It's still apache so I don't really think that should be an issue.

**Comment by hanakin** [comment]
@marc1706 i am referring to this stuff <REMOVED> I have no clue where to or how to edit this stuff. My file in no way resembles anything from the diff you posted

**Comment by marc1706** [comment]
@hanakin that is actually inside the phpbb-website repo. I'll have to update both instructions fully still and put this into one instruction only.

**Comment by hanakin** [comment]
ideally it should just be in website readme 😜

**Comment by paul999** [comment]
Ideally it would require no manual at all ;)

**Comment by hanakin** [comment]
blasphamy!

**Comment by hanakin** [comment]
Review checklist
- [x] About
- [x] Downloads
- [x] Customise/Titania
- [x] Support/KB
- [x] Development/Ideas
- [x] Blog
- [x] Community
- [x] Hosting
- [x] Other/Rdy to merge

This is a list of everything that needs reviewed before we are rdy to merge this, however I do have plans for when I would like this to be merged...that is what other means

**Comment by hanakin** [comment]
ok this is ready to be merged

**Comment by paul999** [comment]
I would like to have a look at this myself first as well. Will do once I am home

**Comment by marc1706** [comment]
While I generally like moving to a wider view I don't like the empty white space on the main page next to "Contribute to phpBB".

**Comment by hanakin** [comment]
@marc1706 that's will not be there anymore, ill update the screenshot. essentially it will be centered

**Comment by hanakin** [comment]
@marc1706 @paul999 up

**Comment by paul999** [comment]
Will look at it this weekend

**Comment by paul999** [comment]
Not sure if I really like how the frontpage looks now, with the extra whitespace at the top besides the 4 buttons.

Otherwise, it looks good to me. Did you also test the blog?

**Comment by marc1706** [comment]
What about adding a new box there, e.g. for ideas?

**Comment by hanakin** [comment]
yes, the blog was tested and more than anything else benefits from this

@marc1706 in truth I would like to completely overhaul that section and redesign all of those buttons correctly as right now they are handled poorly making for a very hacky conversion, but that would require additional prs to the other repo since the HTML would need to be changed and I would need to make all the artwork

**Comment by paul999** [comment]
It think we should overhaul that section now. There is no real need to hurry with merging this PR, and the new view of the icons is not great at all. Having multiple PRs should not be a issue really.

**Comment by hanakin** [comment]
@paul999 the hurry was actually the blog I wanted to push the post about the theme and it's really narrow to showcase anything well.

screenshot 2017-10-21 13 46 27

**Comment by hanakin** [comment]
could do something like this for now

screenshot 2017-10-21 14 38 02
screenshot 2017-10-21 14 39 35
screenshot 2017-10-21 14 39 35
screenshot 2017-10-21 14 39 35 2
screenshot 2017-10-21 14 39 35 3

**Comment by paul999** [comment]
That looks fine with me, much better as with the whitespace

**Comment by marc1706** [comment]
Yep, I agree. That would be a viable solution for now.

**Comment by hanakin** [comment]
ok if there is no problem then can we merge and update the website. Then I will publish the theme post

**Pull request merged**
