### PR TITLE
[WIP] Gulp

### PR DESCRIPTION
**Pull request by callumacrae**
Currently broken by https://github.com/2createStudio/postcss-sprites/issues/8

### CODE REVIEW

**Comment by vvasilev-** [comment]
https://github.com/2createStudio/postcss-sprites/commit/2945541529c2716c2fe477f3cff8c9367bdbd35c

**Comment by callumacrae** [comment]
@vvasilev- Thank you! :tada:

**Comment by michaelcullum** [comment]
This still a WIP?

**Comment by callumacrae** [comment]
yes

**Pull request closed without merging**
